#!/bin/bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
# setup-directory.sh — Multi-user directory setup for PCS reference architecture.
#
# Single script for both login node (LDAP server) and compute nodes (SSSD client).
# Called from CNG UserData when DirectoryService != "none".
#
# Usage: setup-directory.sh <role>
#   role = "server"  (login node — installs slapd, creates base OUs)
#          "client"  (compute node — installs SSSD, points at LDAP server)
#
# IMPORTANT — single login node only when DirectoryService=OpenLDAP-LoginNode:
#   The OpenLDAP server runs on THE login node and its DB lives on shared
#   /home (OpenZFS). This design assumes exactly ONE login node (server). Do
#   NOT scale the login node group above MinCount=MaxCount=1 with the directory
#   enabled: multiple login nodes would each tag themselves directory-role=server
#   (clients would pick an arbitrary one) and each run a slapd against the same
#   /home/ldap-db MDB files (concurrent-open corruption). For HA multi-server
#   directory, use a managed backend (Simple AD / Managed AD) instead — that is
#   the planned DirectoryService=SimpleAD / ManagedAD extension path.
#
# Environment variables (from UserData):
#   LDAP_DOMAIN_SUFFIX  — e.g. "dc=cluster,dc=internal"
#   LDAP_DOMAIN         — e.g. "cluster.internal" (derived from suffix)
#   LDAP_ADMIN_PASSWORD — auto-generated by UserData (server role only)
#   CLUSTER_ID          — PCS cluster ID (for SSM parameter path)
#   LDAP_SERVER_URI     — e.g. "ldap://10.1.x.x" (client role; empty = discover)
#   DIRECTORY_DNS_IPS   — comma-separated DNS IPs (future SimpleAD; empty = discover login IP)
#   S3_BUCKET           — bucket holding the scripts (server role; to install the
#                         ldap-add-user.sh helper onto /usr/local/bin)
#   S3_KEY_PREFIX       — key prefix for the scripts (default "templates/")

set -euo pipefail

ROLE="${1:-client}"
LDAP_DOMAIN_SUFFIX="${LDAP_DOMAIN_SUFFIX:-dc=cluster,dc=internal}"
LDAP_DOMAIN="${LDAP_DOMAIN:-cluster.internal}"
LDAP_DB_DIR="/home/ldap-db"

export DEBIAN_FRONTEND=noninteractive

###############################################################################
# OS-family detection. Debian/Ubuntu and RHEL/Rocky 9 diverge substantially for
# the directory service: package names, the slapd config flow (debconf vs
# slappasswd+olc), the slapd.d path, the openldap service user, SELinux vs
# AppArmor, and PAM/NSS wiring (authselect on RHEL). Everything below branches
# on OS_FAMILY. NOTE: the RHEL server-role OpenLDAP flow is more involved and
# should be validated on a live Rocky 9 login node (see docs/ROCKY9-AMI.md).
###############################################################################
OS_ID=$( . /etc/os-release 2>/dev/null; echo "${ID:-}" )
OS_ID_LIKE=$( . /etc/os-release 2>/dev/null; echo "${ID_LIKE:-}" )
case "${OS_ID}:${OS_ID_LIKE}" in
    ubuntu:*|debian:*|*:*debian*) OS_FAMILY=debian ;;
    rocky:*|rhel:*|centos:*|almalinux:*|*:*rhel*|*:*fedora*) OS_FAMILY=rhel ;;
    *) echo "[directory] ERROR: unsupported OS (ID=${OS_ID} ID_LIKE=${OS_ID_LIKE})"; exit 1 ;;
esac
if [ "${OS_FAMILY}" = "rhel" ]; then
    OPENLDAP_USER=ldap
    SLAPD_D_DIR=/etc/openldap/slapd.d
else
    OPENLDAP_USER=openldap
    SLAPD_D_DIR=/etc/ldap/slapd.d
fi
echo "[directory] OS family: ${OS_FAMILY} (openldap user: ${OPENLDAP_USER})"

# AWS CLI calls below (ssm put-parameter, ec2 describe-instances) pass no
# --region: on EC2 the CLI resolves both credentials and region from the
# instance's IMDS credential provider (it obtains the IMDSv2 token itself, even
# under HttpTokens=required). Reading placement/region with a plain curl would
# need a manual token and return empty without one, so we deliberately let the
# CLI handle it instead of passing a (possibly empty) --region.

echo "[directory] Role: ${ROLE}"
echo "[directory] Domain: ${LDAP_DOMAIN} (${LDAP_DOMAIN_SUFFIX})"

###############################################################################
# apt helpers — at first boot cloud-init's own unattended-upgrades/apt run can
# still hold the dpkg lock, so a bare `apt-get install` fails with
# "Could not get lock /var/lib/dpkg/lock-frontend". Wait for the lock to clear,
# then run apt-get with built-in retries. Mirrors install-enroot-pyxis.sh.
###############################################################################
wait_for_apt_lock() {
    local waited=0
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 \
       || fuser /var/lib/dpkg/lock >/dev/null 2>&1 \
       || fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do
        if [ "$waited" -ge 300 ]; then
            echo "[directory] WARNING: dpkg lock still held after ${waited}s; proceeding anyway."
            break
        fi
        echo "[directory] Waiting for apt/dpkg lock to clear (${waited}s)..."
        sleep 10
        waited=$((waited + 10))
    done
}

apt_get() {
    wait_for_apt_lock
    local attempt
    for attempt in 1 2 3; do
        if DEBIAN_FRONTEND=noninteractive apt-get "$@"; then
            return 0
        fi
        echo "[directory] apt-get $* failed (attempt ${attempt}/3); waiting for lock and retrying..."
        wait_for_apt_lock
        sleep 5
    done
    echo "[directory] ERROR: apt-get $* failed after 3 attempts."
    return 1
}

# Refresh package metadata (apt update on Debian; dnf makecache on RHEL).
pkg_refresh() {
    if [ "${OS_FAMILY}" = "debian" ]; then
        apt_get update -qq
    else
        dnf -y makecache || true
    fi
}

# Install packages for the current OS family. Callers pass the RHEL package list
# via PKGS_RHEL and the Debian list via PKGS_DEBIAN env before calling, since the
# names differ (e.g. libpam-sss vs sssd; slapd vs openldap-servers).
pkg_install() {
    if [ "${OS_FAMILY}" = "debian" ]; then
        apt_get install -y ${PKGS_DEBIAN}
    else
        dnf -y install ${PKGS_RHEL}
    fi
}

###############################################################################
# SERVER role — login node: install slapd + configure
###############################################################################
setup_server() {
    LDAP_ADMIN_PASSWORD="${LDAP_ADMIN_PASSWORD:?LDAP_ADMIN_PASSWORD must be set}"
    CLUSTER_ID="${CLUSTER_ID:-unknown}"

    # Idempotent admin password: UserData generates a fresh random password on
    # every boot, but the user DB on /home/ldap-db is PERSISTENT (survives login
    # node replacement). If we let each replacement re-randomise the password,
    # the SSM parameter (and slapd's olcRootPW) silently change while the data
    # stays — breaking any admin who cached the old password. So if a password
    # already exists in SSM for this cluster, REUSE it: slapd is then configured
    # (via debconf below) with the same password the DB was created under, and
    # the final put-parameter becomes a no-op overwrite. Only the very first
    # login node (empty SSM) keeps the UserData-generated random password.
    if [ "${CLUSTER_ID}" != "unknown" ]; then
        local existing_pw
        existing_pw=$(aws ssm get-parameter \
            --name "/pcs/${CLUSTER_ID}/ldap/admin-password" \
            --with-decryption --query 'Parameter.Value' --output text 2>/dev/null || echo "")
        if [ -n "$existing_pw" ] && [ "$existing_pw" != "None" ]; then
            echo "[directory-server] Reusing existing admin password from SSM (login node replacement / re-run)."
            LDAP_ADMIN_PASSWORD="$existing_pw"
        fi
    fi

    echo "[directory-server] Refreshing package metadata..."
    pkg_refresh

    # slapd's systemd unit name differs by distro: 'slapd' on Debian, 'slapd' also
    # on RHEL openldap-servers (the unit is named slapd there too), so SLAPD_SVC is
    # 'slapd' in both — but the INSTALL + preseed flow is completely different.
    SLAPD_SVC=slapd

    if [ "${OS_FAMILY}" = "debian" ]; then
        echo "[directory-server] Installing slapd + ldap-utils (Debian)..."
        debconf-set-selections <<EOF
slapd slapd/internal/adminpw password ${LDAP_ADMIN_PASSWORD}
slapd slapd/internal/generated_adminpw password ${LDAP_ADMIN_PASSWORD}
slapd slapd/password2 password ${LDAP_ADMIN_PASSWORD}
slapd slapd/password1 password ${LDAP_ADMIN_PASSWORD}
slapd slapd/domain string ${LDAP_DOMAIN}
slapd shared/organization string PCSCluster
slapd slapd/purge_database boolean false
slapd slapd/move_old_database boolean false
slapd slapd/no_configuration boolean false
EOF
        PKGS_DEBIAN="slapd ldap-utils" pkg_install
    else
        echo "[directory-server] Installing openldap-servers + clients (RHEL/Rocky)..."
        # openldap-servers is in the CRB/PowerTools repo on RHEL 9; ensure it's on.
        dnf -y install epel-release || true
        dnf config-manager --set-enabled crb 2>/dev/null || dnf config-manager --set-enabled powertools 2>/dev/null || true
        PKGS_RHEL="openldap-servers openldap-clients" pkg_install
        # RHEL has no debconf preseed. Configure the MDB suffix + admin DN + rootpw
        # directly against cn=config after the service is up (below). Seed the config
        # DB from the shipped template if this is a first install.
        if [ ! -d "${SLAPD_D_DIR}/cn=config" ] && [ -d /usr/share/openldap-servers ]; then
            install -d -m 0700 -o "${OPENLDAP_USER}" -g "${OPENLDAP_USER}" "${SLAPD_D_DIR}"
        fi
    fi

    echo "[directory-server] Configuring LDAP DB on shared storage (${LDAP_DB_DIR})..."
    systemctl stop "${SLAPD_SVC}" || true

    # Move DB to shared OpenZFS (/home) if not already there
    if [ ! -d "${LDAP_DB_DIR}" ]; then
        mkdir -p "${LDAP_DB_DIR}"
        if [ -d /var/lib/ldap ] && [ "$(ls -A /var/lib/ldap 2>/dev/null)" ]; then
            cp -a /var/lib/ldap/* "${LDAP_DB_DIR}/"
        fi
        chown -R "${OPENLDAP_USER}:${OPENLDAP_USER}" "${LDAP_DB_DIR}"
    fi

    # Update slapd DB directory in cn=config (slapd.d path differs by distro).
    if [ -d "${SLAPD_D_DIR}" ]; then
        MDB_LDIF=$(find "${SLAPD_D_DIR}" -name "olcDatabase*mdb*" -o -name "olcDatabase*hdb*" | head -1)
        if [ -n "$MDB_LDIF" ] && grep -q "olcDbDirectory" "$MDB_LDIF"; then
            sed -i "s|olcDbDirectory:.*|olcDbDirectory: ${LDAP_DB_DIR}|" "$MDB_LDIF"
        fi
    fi

    if [ "${OS_FAMILY}" = "debian" ]; then
        # AppArmor: allow slapd to access /home/ldap-db (Debian confines slapd via AppArmor).
        if [ -f /etc/apparmor.d/usr.sbin.slapd ]; then
            if ! grep -q "${LDAP_DB_DIR}" /etc/apparmor.d/usr.sbin.slapd; then
                sed -i "/\/var\/lib\/ldap\/ r,/a\\  ${LDAP_DB_DIR}/ r," /etc/apparmor.d/usr.sbin.slapd
                sed -i "/\/var\/lib\/ldap\/\*\* rwk,/a\\  ${LDAP_DB_DIR}/** rwk," /etc/apparmor.d/usr.sbin.slapd
                apparmor_parser -r /etc/apparmor.d/usr.sbin.slapd 2>/dev/null || true
            fi
        fi
    else
        # RHEL/Rocky: SELinux (not AppArmor) confines slapd. Label the shared DB dir
        # with the slapd DB type so an enforcing system lets slapd read/write it, and
        # allow reading home dirs over NFS. Best-effort: no-ops if SELinux is disabled.
        if command -v semanage >/dev/null 2>&1; then
            semanage fcontext -a -t slapd_db_t "${LDAP_DB_DIR}(/.*)?" 2>/dev/null || true
        fi
        restorecon -Rv "${LDAP_DB_DIR}" 2>/dev/null || true
        setsebool -P use_nfs_home_dirs 1 2>/dev/null || true
    fi

    chown -R "${OPENLDAP_USER}:${OPENLDAP_USER}" "${LDAP_DB_DIR}"
    systemctl start "${SLAPD_SVC}"
    systemctl enable "${SLAPD_SVC}"

    # RHEL/Rocky: openldap-servers ships with an EMPTY cn=config (no suffix/admin/rootpw
    # like Debian's debconf sets up). Seed the MDB suffix, admin DN, and rootpw against
    # cn=config now that slapd is running. Debian already has these from debconf.
    if [ "${OS_FAMILY}" = "rhel" ]; then
        local hashed_pw
        hashed_pw=$(slappasswd -s "${LDAP_ADMIN_PASSWORD}")
        # Find the MDB database DN in cn=config (usually olcDatabase={2}mdb).
        ldapmodify -Y EXTERNAL -H ldapi:/// 2>/dev/null <<EOF || echo "[directory-server] NOTE: cn=config seed may need manual review on RHEL (see docs/ROCKY9-AMI.md)"
dn: olcDatabase={2}mdb,cn=config
changetype: modify
replace: olcSuffix
olcSuffix: ${LDAP_DOMAIN_SUFFIX}
-
replace: olcRootDN
olcRootDN: cn=admin,${LDAP_DOMAIN_SUFFIX}
-
replace: olcRootPW
olcRootPW: ${hashed_pw}
EOF
    fi

    # Wait for slapd
    for i in $(seq 1 10); do
        ldapsearch -x -H ldap://localhost -b "" -s base namingContexts >/dev/null 2>&1 && break
        sleep 1
    done

    echo "[directory-server] Creating base OUs..."
    ldapadd -x -H ldap://localhost -D "cn=admin,${LDAP_DOMAIN_SUFFIX}" -w "${LDAP_ADMIN_PASSWORD}" <<EOF 2>/dev/null || true
dn: ou=People,${LDAP_DOMAIN_SUFFIX}
objectClass: organizationalUnit
ou: People
EOF
    ldapadd -x -H ldap://localhost -D "cn=admin,${LDAP_DOMAIN_SUFFIX}" -w "${LDAP_ADMIN_PASSWORD}" <<EOF 2>/dev/null || true
dn: ou=Groups,${LDAP_DOMAIN_SUFFIX}
objectClass: organizationalUnit
ou: Groups
EOF
    # Default group
    ldapadd -x -H ldap://localhost -D "cn=admin,${LDAP_DOMAIN_SUFFIX}" -w "${LDAP_ADMIN_PASSWORD}" <<EOF 2>/dev/null || true
dn: cn=clusterusers,ou=Groups,${LDAP_DOMAIN_SUFFIX}
objectClass: posixGroup
cn: clusterusers
gidNumber: 3000
EOF

    # Persist admin password — prefer SSM (access-controlled, auditable).
    # No explicit --region: the AWS CLI resolves it from the instance's IMDS
    # credential provider (reading placement/region directly would need an
    # IMDSv2 token).
    if aws ssm put-parameter \
         --name "/pcs/${CLUSTER_ID}/ldap/admin-password" \
         --value "${LDAP_ADMIN_PASSWORD}" \
         --type SecureString \
         --overwrite 2>/dev/null; then
        echo "[directory-server] Admin password stored in SSM: /pcs/${CLUSTER_ID}/ldap/admin-password"
    else
        echo "${LDAP_ADMIN_PASSWORD}" > "${LDAP_DB_DIR}/.admin-password"
        chmod 600 "${LDAP_DB_DIR}/.admin-password"
        chown "${OPENLDAP_USER}:${OPENLDAP_USER}" "${LDAP_DB_DIR}/.admin-password"
        echo "[directory-server] WARNING: SSM put failed. Password saved to ${LDAP_DB_DIR}/.admin-password"
    fi

    # Install the ldap-add-user helper alongside this script so admins have it
    # on PATH (/usr/local/bin) on the login node. Fetched from the same S3
    # location this script came from (S3_BUCKET/S3_KEY_PREFIX passed by UserData);
    # falls back to a no-op with a hint if those are unset.
    if [ -n "${S3_BUCKET:-}" ]; then
        if aws s3 cp "s3://${S3_BUCKET}/${S3_KEY_PREFIX:-templates/}scripts/ldap-add-user.sh" \
             /usr/local/bin/ldap-add-user.sh 2>/dev/null; then
            chmod 755 /usr/local/bin/ldap-add-user.sh
            echo "[directory-server] Installed helper: /usr/local/bin/ldap-add-user.sh"
        else
            echo "[directory-server] WARNING: could not fetch ldap-add-user.sh from s3://${S3_BUCKET}/${S3_KEY_PREFIX:-templates/}scripts/ — add users with raw ldapadd (see USER-MANAGEMENT.md)."
        fi
    else
        echo "[directory-server] NOTE: S3_BUCKET unset; skipping ldap-add-user.sh install. Add users with raw ldapadd (see USER-MANAGEMENT.md)."
    fi

    # Also configure SSSD on the login node itself (so getent works locally)
    setup_client_internal "ldap://localhost"

    echo "[directory-server] OpenLDAP server ready."
    echo "[directory-server] Admin DN: cn=admin,${LDAP_DOMAIN_SUFFIX}"
}

###############################################################################
# CLIENT role — compute node: install SSSD + configure LDAP provider
###############################################################################
setup_client() {
    # Determine LDAP server URI
    local server_uri="${LDAP_SERVER_URI:-}"

    if [ -z "$server_uri" ]; then
        # Discover login node IP
        if [ -n "${DIRECTORY_DNS_IPS:-}" ]; then
            # Future: SimpleAD — use provided DNS IPs
            server_uri="ldap://${DIRECTORY_DNS_IPS%%,*}"
        else
            # OpenLDAP-LoginNode — discover the directory server's private IP via
            # its EC2 tags (pcs-cluster-id + directory-role=server). The
            # directory-role tag is owned by the multi-user feature and is
            # independent of the monitoring stack's monitoring-role tag. The AWS
            # CLI auto-resolves the region from the instance's IMDS credential
            # provider, so no explicit --region (which would need an IMDSv2 token
            # to read placement/region) is required.
            if [ -z "${CLUSTER_ID:-}" ]; then
                echo "[directory-client] ERROR: CLUSTER_ID is empty; cannot discover directory server. LDAP client not configured."
                return 1
            fi
            # Retry the tag lookup with backoff: a compute node can boot before
            # the login node has finished tagging itself directory-role=server
            # (scale-up race, or a compute node coming up right after a login
            # node replacement). A single one-shot lookup would leave the node
            # permanently LDAP-less until the next reboot, so poll for up to
            # ~5 min. The describe-instances filter already scopes to this
            # cluster's running server only.
            local login_ip=""
            local attempt
            for attempt in $(seq 1 30); do
                login_ip=$(aws ec2 describe-instances \
                    --filters "Name=tag:pcs-cluster-id,Values=${CLUSTER_ID}" \
                              "Name=tag:directory-role,Values=server" \
                              "Name=instance-state-name,Values=running" \
                    --query 'Reservations[0].Instances[0].PrivateIpAddress' \
                    --output text 2>/dev/null || echo "")
                if [ -n "$login_ip" ] && [ "$login_ip" != "None" ]; then
                    break
                fi
                echo "[directory-client] Directory server not found yet (attempt ${attempt}/30); retrying in 10s..."
                sleep 10
            done
            if [ -z "$login_ip" ] || [ "$login_ip" = "None" ]; then
                echo "[directory-client] ERROR: could not discover directory server IP after retries (CLUSTER_ID=${CLUSTER_ID}, directory-role=server). Check the compute node's IAM role has ec2:DescribeInstances and that the login node is running. LDAP client not configured."
                return 1
            fi
            server_uri="ldap://${login_ip}"
        fi
    fi

    setup_client_internal "$server_uri"
}

###############################################################################
# Internal: configure SSSD (shared by server + client roles)
###############################################################################
setup_client_internal() {
    local server_uri="$1"

    echo "[directory-client] Refreshing package metadata..."
    pkg_refresh

    echo "[directory-client] Installing SSSD..."
    # sssd-tools provides sss_cache, needed to invalidate the SSSD cache after a
    # user is deleted/modified in LDAP (otherwise the change is not visible until
    # the cache entry's TTL expires — see USER-MANAGEMENT.md "Deleting a user").
    # Package names differ: Debian splits pam/nss into libpam-sss/libnss-sss;
    # RHEL/Rocky bundles them into sssd + sssd-ldap and uses oddjob-mkhomedir.
    PKGS_DEBIAN="sssd sssd-tools libpam-sss libnss-sss ldap-utils" \
    PKGS_RHEL="sssd sssd-tools sssd-ldap oddjob-mkhomedir openldap-clients authselect" \
        pkg_install

    echo "[directory-client] Configuring SSSD (server: ${server_uri})..."
    cat > /etc/sssd/sssd.conf <<EOF
[sssd]
config_file_version = 2
services = nss, pam
domains = ${LDAP_DOMAIN}

[domain/${LDAP_DOMAIN}]
id_provider = ldap
auth_provider = ldap
ldap_uri = ${server_uri}
ldap_search_base = ${LDAP_DOMAIN_SUFFIX}
ldap_user_search_base = ou=People,${LDAP_DOMAIN_SUFFIX}
ldap_group_search_base = ou=Groups,${LDAP_DOMAIN_SUFFIX}
cache_credentials = true
enumerate = true
default_shell = /bin/bash
fallback_homedir = /home/%u
min_id = 1001
max_id = 60000
EOF
    chmod 600 /etc/sssd/sssd.conf

    if [ "${OS_FAMILY}" = "debian" ]; then
        # Enable pam_mkhomedir (Debian: edit common-session directly).
        if ! grep -q pam_mkhomedir /etc/pam.d/common-session; then
            echo "session optional pam_mkhomedir.so skel=/etc/skel umask=0022" >> /etc/pam.d/common-session
        fi
        # Configure NSS to consult sss (Debian: edit nsswitch.conf directly).
        sed -i 's/^passwd:.*/passwd:         files systemd sss/' /etc/nsswitch.conf
        sed -i 's/^group:.*/group:          files systemd sss/' /etc/nsswitch.conf
        sed -i 's/^shadow:.*/shadow:         files sss/' /etc/nsswitch.conf
    else
        # RHEL/Rocky: use authselect to wire NSS + PAM for sssd (the supported way;
        # hand-editing nsswitch.conf/system-auth is overwritten by authselect).
        # 'with-mkhomedir' enables pam_oddjob_mkhomedir for auto home creation.
        authselect select sssd with-mkhomedir --force 2>/dev/null || authselect select sssd --force 2>/dev/null || true
        systemctl enable --now oddjobd 2>/dev/null || true
        # SELinux: allow login/home over NFS (OpenZFS /home) on the client too.
        setsebool -P use_nfs_home_dirs 1 2>/dev/null || true
    fi

    systemctl enable sssd
    systemctl restart sssd

    echo "[directory-client] SSSD configured. Server: ${server_uri}"
}

###############################################################################
# Main
###############################################################################
case "$ROLE" in
    server)
        setup_server
        ;;
    client)
        setup_client
        ;;
    *)
        echo "Usage: $0 <server|client>"
        exit 1
        ;;
esac
